backend:
  name: github
  repo: TidewaterWomensSoccerLeague/twsl_web
  branch: master

publish_mode: editorial_workflow
media_folder: "site/static/uploads" 
public_folder: "uploads"

collections:
- label: "about"
  name: "about"
  folder: "site/content/about"
  create: true
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "faqs"
  name: "FAQs" 
  folder: "site/content/faqs" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "schedule" 
  name: "schedule" 
  folder: "site/content/schedule" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "rosters"
  name: "rosters"
  folder: "site/content/teams" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "registration" 
  name: "registration" 
  folder: "site/content/registration" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "board" 
  name: "board" 
  folder: "site/content/board" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "contact" 
  name: "contact" 
  folder: "site/content/contact" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}

- label: "shop" 
  name: "shop" 
  folder: "site/content/shop" 
  create: true 
  fields: 
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "datetime"}